language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os:
    - linux

env:
    global:
        - NUMPY_VERSION=1.9
        - PYTHON_VERSION=2.7
        - ASTROPY_VERSION=1.0.2

install:
    - source .travis/setup_environment.sh

script:
    - python prepare_deploy.py run

deploy:
    provider: script
    script: INTERACTIVE=false deploy
    on:
        repo: eteq/astropy-tutorials
        branch: staging