language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os:
    - linux

env:
    global:
        - NUMPY_VERSION=1.9
        - PYTHON_VERSION=2.7
        - ASTROPY_VERSION=1.0.2
        - GH_REF: github.com/eteq/astropy-tutorials.git
        - secure: "h8WZbvCUX4yHrx9UcV8sRrBxmRwruDaqOuTZR85lEQFevRhzW8BEUJmhdIweROZxMK66zBUnLpjeMnt/B16U0f9fRAWNzIEFadBrPzHnAoBhY79+Xz5pn+lqz9j8Kl2uv4fUtEzQAipN06o5JGtDrjRRxscoXbQLtvewlo2tIK4="

install:
    - source .travis/setup_environment.sh

script:
    - python prepare_deploy.py run

deploy:
    provider: script
    script: ./travis_deploy
    on:
        repo: eteq/astropy-tutorials
        branch: staging